version: '3'

services:
  voltronic-mqtt:

    # We're now (finally) supporting Multi-Arch builds (via Github actions) on Docker Hub!
    build: .

    # Uncomment if you want to build your own local version.
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev


    container_name: voltronic-mqtt

    privileged: true
    restart: always

    volumes:
        - /mnt/data/supervisor/media/ha-inverter-mqtt-agent-custom/config/:/etc/inverter/

    devices:
    #  - "/dev/mem:/dev/mem"

    # Serial Port Mapping...
      - /dev/ttyS6:/dev/ttyS6

  # Used to auto-update images as we release new versions...
  watchtower:
    # Please see the following for configuration options:
    #    https://containrrr.github.io/watchtower/container-selection/
    image: containrrr/watchtower
    container_name: watchtower

    restart: always
    privileged: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 500

